### ISSUE TITLE
Optimize Circuit Design for High-Level Field (Fq6, Fq12) Operations

### ISSUE THREAD

**Issue by twliu-dorian** [NethermindEth/cairo-plonk-verifier#16]
Ensure that circuit implementations are designed as high-level as possible. Higher-degree field operations should not rely on lower-field implementations unless the computational complexity becomes impractical.

The implementation could be done by just copying and pasting the lower levels (Fq1, Fq2) into high-level fields.

**Comment by memarin** [comment]
Need to merge https://github.com/NethermindEth/cairo-plonk-verifier/pull/14 before this is merged

**Comment by memarin** [comment]
Already included in issue #6
