### ISSUE TITLE
Creating circuit compatible field structures and operations

### ISSUE THREAD

**Issue by danielntmd** [NethermindEth/cairo-plonk-verifier#6]
Let's create a new base field 
`struct Fq {
    c0: 384
}`

And implement the field operations trait as circuits. The files relevant will be fq_1, fq_2, fq_6, fq_12. Let's keep the old field implementations as reference for now with the plan to slowly phase it out.

Let's write the circuits as high level as possible, ie. higher degree field operations should not depend on the lower field implementations unless complexity is too high. (might run into complexity problems at fq_6 and higher).

**Comment by danielntmd** [comment]
We can break these down into multiple commits

**Comment by memarin** [comment]
Need to update the target date
