### ISSUE TITLE
Group operations for Field degree 2 as circuits

### ISSUE THREAD

**Issue by danielntmd** [NethermindEth/cairo-plonk-verifier#7]
Let's create a new ECOperations trait that that implements the add, double, and multiply functions as circuits for the AffineG2 type. 

We can choose to ignore the other functions in this trait as we will be incorporating their circuits directly into these 3 operations, but feel free to add for completeness. 

Relevant files will be the groups file.

**Comment by memarin** [comment]
@Vazquez-bit i put Nov 21 as the target date for this. Let me know if that is reasonable for you

**Comment by Vazquez-bit** [comment]
Yes, I think it can work. I'll keep updating here with any challenges I may encounter while doing it

**Comment by memarin** [comment]
@Vazquez-bit is travelling on the 20th Nov

**Comment by memarin** [comment]
Pending @danielntmd review. Need to update the target date

**Comment by memarin** [comment]
Will be covered in #31
